server:
  port: 8087
girl:
  cupSize: B
  age: 18
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters,去掉后监控界面无法统计SQL,wall用于防火墙
    filters: stat,wall,log4j
    maxActive: 20
    initalSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    validtionQuery: select 1 from dual
    testWhiledle: true
    testOnBorrow: false
    testOnReturn: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000

#    jedis:
#      pool:
#        max-idle: 20
#        min-idle: 1
#        max-active: 20
#        max-wait: 60000s
#      database: 0